# Generated by Django 5.0.6 on 2024-06-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=225, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='active', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=225, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('sector', models.CharField(blank=True, max_length=225, null=True)),
                ('log_in', models.DateTimeField(blank=True, null=True)),
                ('log_out', models.DateTimeField(blank=True, null=True)),
                ('position', models.CharField(blank=True, default='company', max_length=7, null=True)),
                ('profile', models.ImageField(blank=True, default='default profile.jpg', null=True, upload_to='company_profile/')),
            ],
        ),
    ]
