# Generated by Django 5.0.6 on 2024-06-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgeneration', '0002_companylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylog',
            name='profile',
            field=models.ImageField(blank=True, default='default profile.jpg', null=True, upload_to='company_profile/'),
        ),
    ]
