# Generated by Django 5.0.6 on 2024-06-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
