# Generated by Django 5.0.6 on 2024-06-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_alter_subscriptionplan_plan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(blank=True, default=False, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
