# Generated by Django 5.0.6 on 2024-06-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_companysubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysubscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
