# Generated by Django 5.0.6 on 2024-06-24 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0006_productservice_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
