# Generated by Django 5.0.6 on 2024-07-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0008_category_productservice_availability_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscription_plans', to='custom_admin.productservice'),
        ),
    ]
