# Generated by Django 5.0.6 on 2024-07-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0010_plan_companysubscription_plan_subscriptionplan_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
