# Generated by Django 5.0.6 on 2024-07-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0011_alter_subscriptionplan_plan_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='products',
            new_name='product',
        ),
    ]
