# Generated by Django 5.0.6 on 2024-07-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0012_rename_products_subscriptionplan_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscription_plan', to='custom_admin.productservice'),
        ),
    ]
