# Generated by Django 5.0.6 on 2024-07-09 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0013_alter_subscriptionplan_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='product',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan', to='custom_admin.productservice'),
        ),
    ]
