# Generated by Django 5.0.6 on 2024-07-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0015_alter_companysubscription_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysubscription',
            name='plan',
        ),
    ]
