# Generated by Django 5.0.6 on 2024-07-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0016_remove_companysubscription_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysubscription',
            old_name='company_name',
            new_name='company',
        ),
    ]
