# Generated by Django 5.0.6 on 2024-07-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0017_rename_company_name_companysubscription_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscription',
            name='period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
