# Generated by Django 5.0.6 on 2024-07-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0018_companysubscription_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscription',
            name='notify_before_expire',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='notify_on_expire',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
